import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // Admin data getters take a leading `_admin: AdminContext` parameter
      // that exists purely as a type-level proof requireAdmin() ran
      // (docs/QA-CHECKLIST.md P2-04) -- never read in the function body.
      // Leading-underscore is the standard "intentionally unused" convention.
      // `ignoreRestSiblings` allows the `const { x: _omit, ...rest } = obj`
      // key-strip idiom (used in tests to build an invalid row).
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", ignoreRestSiblings: true },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage` (gitignored) -- not source to lint.
    "coverage/**",
  ]),
]);

export default eslintConfig;
